export const products = [
  {
    image: "./product1.svg"
  }, {
    image: "./product2.svg"
  }, {
    image: "./product3.svg"
  }, {
    image: "./product4.svg"
  },
];

export const blogs = [
  {
    id: 1,
    domain: 'Coding',
    subDomain: 'Web Designing',
    blogVideoPlayImg: './blogVideoPlay.svg',
    BlogImg: 'blog1.svg',
    alt: 'Blog 1',
    title: 'Integer Maecenas Eget Viverra',
    authorImg: './authorImg.svg',
    authName: 'Joanna Wellick',
    blogDate: 'June 28, 2018',
    shareLink: 'https:google.com',
    shareIcon: './shareIcon.svg',
    shares: '1K shares',
    data: 'Aenean eleifend ante maecenas pulvinar montes lorem et pede dis dolor pretium donec dictum. Vici consequat justo enim. Venenatis eget adipiscing luctus lorem.',
    viewPostLink: '/blog1',
  },
  {
    id: 2,
    domain: 'Coding',
    subDomain: 'Web Designing',
    blogVideoPlayImg: './blogVideoPlay.svg',
    BlogImg: 'blog2.svg',
    alt: 'Blog 2',
    title: 'Integer Maecenas Eget Viverra',
    authorImg: './authorImg.svg',
    authName: 'Joanna Wellick',
    blogDate: 'June 28, 2018',
    shareLink: 'https:google.com',
    shareIcon: './shareIcon.svg',
    shares: '1K shares',
    data: 'Aenean eleifend ante maecenas pulvinar montes lorem et pede dis dolor pretium donec dictum. Vici consequat justo enim. Venenatis eget adipiscing luctus lorem.',
    viewPostLink: '/blog2',
  },
  {
    id: 3,
    domain: 'Coding',
    subDomain: 'Web Designing',
    blogVideoPlayImg: './blogVideoPlay.svg',
    BlogImg: 'blog3.svg',
    alt: 'Blog 3',
    title: 'Integer Maecenas Eget Viverra',
    authorImg: './authorImg.svg',
    authName: 'Joanna Wellick',
    blogDate: 'June 28, 2018',
    shareLink: 'https:google.com',
    shareIcon: './shareIcon.svg',
    shares: '1K shares',
    data: 'Aenean eleifend ante maecenas pulvinar montes lorem et pede dis dolor pretium donec dictum. Vici consequat justo enim. Venenatis eget adipiscing luctus lorem.',
    viewPostLink: '/blog3',
  },
  {
    id: 4,
    domain: 'Coding',
    subDomain: 'Web Designing',
    blogVideoPlayImg: './blogVideoPlay.svg',
    BlogImg: 'blog4.svg',
    alt: 'Blog 4',
    title: 'Integer Maecenas Eget Viverra',
    authorImg: './authorImg.svg',
    authName: 'Joanna Wellick',
    blogDate: 'June 28, 2018',
    shareLink: 'https:google.com',
    shareIcon: './shareIcon.svg',
    shares: '1K shares',
    data: 'Aenean eleifend ante maecenas pulvinar montes lorem et pede dis dolor pretium donec dictum. Vici consequat justo enim. Venenatis eget adipiscing luctus lorem.',
    viewPostLink: '/blog4',
  }, {
    id: 5,
    domain: 'Coding',
    subDomain: 'Web Designing',
    blogVideoPlayImg: './blogVideoPlay.svg',
    BlogImg: 'blog4.svg',
    alt: 'Blog 5',
    title: 'Integer Maecenas Eget Viverra',
    authorImg: './authorImg.svg',
    authName: 'Joanna Wellick',
    blogDate: 'June 28, 2018',
    shareLink: 'https:google.com',
    shareIcon: './shareIcon.svg',
    shares: '1K shares',
    data: 'Aenean eleifend ante maecenas pulvinar montes lorem et pede dis dolor pretium donec dictum. Vici consequat justo enim. Venenatis eget adipiscing luctus lorem.',
    viewPostLink: '/blog5',
  },
  {
    id: 6,
    domain: 'Coding',
    subDomain: 'Web Designing',
    blogVideoPlayImg: './blogVideoPlay.svg',
    BlogImg: 'blog4.svg',
    alt: 'Blog 6',
    title: 'Integer Maecenas Eget Viverra',
    authorImg: './authorImg.svg',
    authName: 'Joanna Wellick',
    blogDate: 'June 28, 2018',
    shareLink: 'https:google.com',
    shareIcon: './shareIcon.svg',
    shares: '1K shares',
    data: 'Aenean eleifend ante maecenas pulvinar montes lorem et pede dis dolor pretium donec dictum. Vici consequat justo enim. Venenatis eget adipiscing luctus lorem.',
    viewPostLink: '/blog5',
  },
]

export const staticBlogs = [
  {
    id: 1,
    img: "./staticBlog.svg",
    title: 'Lorem ipsum dolor sit amet consectetur.',
    blogdate: '21 March 2021',
  }, {
    id: 2,
    img: "./staticBlog.svg",
    title: 'Lorem ipsum dolor sit amet consectetur.',
    blogdate: '21 March 2021',
  }, {
    id: 2,
    img: "./staticBlog.svg",
    title: 'Lorem ipsum dolor sit amet consectetur.',
    blogdate: '21 March 2021',
  },
]